version: "3"
services:
  front:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    tty: true
    command: sh -c 'npm start'
  
  db:
    image: mariadb:10.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
    - basic-auth-network

  web:
    #buildをちゃんと書かないと、DockerfileのCOPYなどが上手く機能しない
    build: 
      context: ./basic-auth-tutorial
      dockerfile: ./Dockerfile
      
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./basic-auth-tutorial:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - basic-auth-network
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  bundle-volume:
  db-data:

networks:
  basic-auth-network:
    external: true
